modLoader = "javafml" #mandatory
loaderVersion = "[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GPLv3"
issueTrackerURL = "https://github.com/TeamMoegMC/Steam-Powered/issues"
[[mods]] #mandatory
modId = "steampowered" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Create: Steam Powered" #mandatory
authors = "[TeamMoeg] YueSha, khjxiaogu, goumo_g"
credits = "We appreciate MRH0 for his code on RPM-FE conversion logic which we adapted in Steam Powered. \nCredits to SpottyTheTurtle for help with remapping. \nCredits to all GitHub contributors."
description = '''
Expanding Create mod to the Steam Age
'''
[[dependencies.steampowered]]
    modId = "forge"
    mandatory = true
    versionRange = "[40.0.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.steampowered]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,1.19)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.steampowered]]
    modId="create"
    mandatory=true
    versionRange="[v0.5.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.steampowered]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.9,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.steampowered]]
    modId="alloyed"
    mandatory=false
    versionRange="[1.18.1,)"
    ordering="AFTER"
    side="BOTH"
